### ISSUE TITLE
NameError: global name 'GameForm' is not defined

### ISSUE THREAD

**Issue by kylebarlow** [jamestwebber/pandemic-statistician#1]
When I try and run the application, I get this error:

> NameError: global name 'GameForm' is not defined

from this section of the code:

```
class BeginForm(FlaskForm):

     ...

     def __init__(self, *args, **kwargs):
       super(GameForm, self).__init__(*args, **kwargs)
```

**Comment by jamestwebber** [comment]
Yeah that's because I just changed it and didn't fix that.

**Comment by kylebarlow** [comment]
Thanks
